/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import database.Db;
import static database.Db.newUser;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ramo828
 */
public class register extends javax.swing.JFrame implements database.IQueries,IMainInterface{


    /**
     * Creates new form register
     */
    public register() {

        initComponents();
    }

    private int hide_windows(){
        this.setVisible(false);
        new login().setVisible(true);
        return 0;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        t_pass = new javax.swing.JTextField();
        t_login = new javax.swing.JTextField();
        t_name = new javax.swing.JTextField();
        t_surname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_number = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        try_text = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        alert_lab = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        mesuk = new javax.swing.JLabel();

        jTextField5.setText("jTextField5");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mesuk v1.0");
        setForeground(new java.awt.Color(109, 114, 236));

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 21)); // NOI18N
        jLabel1.setText("Login: ");

        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 21)); // NOI18N
        jLabel2.setText("Şifrə: ");

        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 21)); // NOI18N
        jLabel3.setText("Ad: ");

        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 21)); // NOI18N
        jLabel4.setText("Soyad: ");

        t_pass.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        t_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passActionPerformed(evt);
            }
        });
        t_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_passKeyPressed(evt);
            }
        });

        t_login.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        t_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_loginActionPerformed(evt);
            }
        });
        t_login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_loginKeyPressed(evt);
            }
        });

        t_name.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });
        t_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_nameKeyPressed(evt);
            }
        });

        t_surname.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        t_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_surnameActionPerformed(evt);
            }
        });
        t_surname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_surnameKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 21)); // NOI18N
        jLabel5.setText("Nömrə: ");

        t_number.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        t_number.setText("+994");
        t_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numberActionPerformed(evt);
            }
        });
        t_number.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_numberKeyPressed(evt);
            }
        });

        jButton1.setText("Qeydiyyat");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        try_text.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        try_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                try_textKeyPressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 21)); // NOI18N
        jLabel7.setText("T. Şifrə: ");

        alert_lab.setFont(new java.awt.Font("Cantarell", 0, 28)); // NOI18N
        alert_lab.setForeground(new java.awt.Color(245, 6, 6));
        alert_lab.setText("----------------------------------------------");

        back.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        back.setText("<--Geri");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel9.setText("Email: ");

        t_email.setFont(new java.awt.Font("Cantarell", 1, 18)); // NOI18N
        t_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_emailActionPerformed(evt);
            }
        });
        t_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_emailKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel11.setText("Mesuk v 1.0");

        mesuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/pp.jpeg"))); // NOI18N
        mesuk.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_number, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(try_text, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_login, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alert_lab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(314, 314, 314))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(mesuk)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(alert_lab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(t_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(try_text, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_surname, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_number, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(t_email, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mesuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passActionPerformed

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_loginActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void t_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_surnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void register() throws SQLException {
        Db d = new Db();
        login l = new login();
        d.init();
        String login = t_login.getText();
        String pass = t_pass.getText();
        String name = t_name.getText();
        String email = t_email.getText();
        String number = t_number.getText();
        String surname = t_surname.getText();
        String try_pass = try_text.getText();
        int regBonus = Integer.parseInt(d.getDataString(1, settingQuery));
        if (login.isEmpty()) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(nullLoginMsg);
        } else if (login.length() > 15) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(LongLoginMsg);
        } else if (pass.isBlank() && try_pass.isBlank()) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(nullPassMsg);
        } else if (pass.length() > 15 && try_pass.length() > 15) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(LongPassMsg);
        } else if (try_pass.length() < 8 && pass.length() < 8) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(limitPass);
        } else if (name.isBlank()) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(nullNameLogin);
        } else if (name.length() > 15) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(LongNameLogin);
        } else if (surname.isBlank()) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(nullSurnameMsg);
        } else if (surname.length() > 15) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(LongSurnameMsg);
        } else if (email.isBlank()) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(nullEmailMsg);
        } else if (login.length() > 25) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(LongEmailMsg);
        } else if (email.indexOf("@") == -1) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(wrongEmail);
        } else if (number.indexOf("+") == -1) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(wrongNumber);
            } else if (d.alreadyInput(login.toLowerCase(),loginVar)) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(existLogin);
        } else if (d.alreadyInput(email.toLowerCase(),emailVar)) {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(existEmail);
        } else if (!pass.equals(try_text.getText())) {
            alert_lab.setForeground(Color.red);

            alert_lab.setText(tryPassError);
        } else if (newUser(
                login.toLowerCase(),
                pass,
                number,
                email,
                name,
                surname,
                regBonus,
                0,
                "",
                "",
                0,
                0)) {
            alert_lab.setForeground(Color.green);
            alert_lab.setText(RefisterSuccessMsg);
            l.setVisible(true);
            l.alert(RefisterSuccessMsg, 5);
            this.setVisible(false);
        } else {
            alert_lab.setForeground(Color.red);
            alert_lab.setText(RefisterUnsuccessMsg);
        }
    }


    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        login l = new login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void t_loginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_loginKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_loginKeyPressed

    private void t_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_passKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_passKeyPressed

    private void try_textKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_try_textKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_try_textKeyPressed

    private void t_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_nameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_nameKeyPressed

    private void t_surnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_surnameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_surnameKeyPressed

    private void t_numberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numberKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_numberKeyPressed

    private void t_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_emailActionPerformed

    }//GEN-LAST:event_t_emailActionPerformed

    private void t_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numberActionPerformed

    }//GEN-LAST:event_t_numberActionPerformed

    private void t_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER)
            try {
            register();
        } catch (SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_t_emailKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alert_lab;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel mesuk;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_login;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_number;
    private javax.swing.JTextField t_pass;
    private javax.swing.JTextField t_surname;
    private javax.swing.JTextField try_text;
    // End of variables declaration//GEN-END:variables
}
