/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cpanel;

import Main.IMainInterface;
import database.Db;
import java.sql.SQLException;

/**
 *
 * @author ramo828
 */
public class showUser extends javax.swing.JFrame implements IMainInterface {

    /**
     * Creates new form showUser
     */
    private int myId = 0;
    private static int job = 0;

    private static Db d = new Db();

    public showUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ad_ = new javax.swing.JLabel();
        soyad_ = new javax.swing.JLabel();
        login_ = new javax.swing.JLabel();
        ID_ = new javax.swing.JLabel();
        email_ = new javax.swing.JLabel();
        nomre_ = new javax.swing.JLabel();
        coin_ = new javax.swing.JLabel();
        msg_num_ = new javax.swing.JLabel();
        job_ = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sts_ = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("User");
        setBackground(new java.awt.Color(173, 183, 229));
        setFont(new java.awt.Font("Alkalami", 1, 24)); // NOI18N
        setForeground(new java.awt.Color(179, 185, 205));

        jLabel1.setBackground(new java.awt.Color(193, 198, 224));
        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(234, 62, 191));
        jLabel1.setText("Ad: ");

        jLabel2.setBackground(new java.awt.Color(193, 198, 224));
        jLabel2.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(234, 62, 191));
        jLabel2.setText("Soyad: ");

        jLabel3.setBackground(new java.awt.Color(193, 198, 224));
        jLabel3.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(234, 62, 191));
        jLabel3.setText("Login: ");

        jLabel4.setBackground(new java.awt.Color(193, 198, 224));
        jLabel4.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(234, 62, 191));
        jLabel4.setText("ID");

        jLabel5.setBackground(new java.awt.Color(193, 198, 224));
        jLabel5.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(234, 62, 191));
        jLabel5.setText("Email:");

        jLabel6.setBackground(new java.awt.Color(193, 198, 224));
        jLabel6.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(234, 62, 191));
        jLabel6.setText("Nömrə");

        jLabel7.setBackground(new java.awt.Color(193, 198, 224));
        jLabel7.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(234, 62, 191));
        jLabel7.setText("Coin: ");

        jLabel8.setBackground(new java.awt.Color(193, 198, 224));
        jLabel8.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(234, 62, 191));
        jLabel8.setText("Mesaj sayı: ");

        ad_.setBackground(new java.awt.Color(193, 198, 224));
        ad_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        ad_.setForeground(new java.awt.Color(234, 62, 191));
        ad_.setText("Ad: ");

        soyad_.setBackground(new java.awt.Color(193, 198, 224));
        soyad_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        soyad_.setForeground(new java.awt.Color(234, 62, 191));
        soyad_.setText("Soyad: ");

        login_.setBackground(new java.awt.Color(193, 198, 224));
        login_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        login_.setForeground(new java.awt.Color(234, 62, 191));
        login_.setText("Login: ");

        ID_.setBackground(new java.awt.Color(193, 198, 224));
        ID_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        ID_.setForeground(new java.awt.Color(234, 62, 191));
        ID_.setText("ID");

        email_.setBackground(new java.awt.Color(193, 198, 224));
        email_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        email_.setForeground(new java.awt.Color(234, 62, 191));
        email_.setText("Email:");

        nomre_.setBackground(new java.awt.Color(193, 198, 224));
        nomre_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        nomre_.setForeground(new java.awt.Color(234, 62, 191));
        nomre_.setText("Nömrə");

        coin_.setBackground(new java.awt.Color(193, 198, 224));
        coin_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        coin_.setForeground(new java.awt.Color(234, 62, 191));
        coin_.setText("Coin: ");

        msg_num_.setBackground(new java.awt.Color(193, 198, 224));
        msg_num_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        msg_num_.setForeground(new java.awt.Color(234, 62, 191));
        msg_num_.setText("Mesaj sayı: ");

        job_.setBackground(new java.awt.Color(193, 198, 224));
        job_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        job_.setForeground(new java.awt.Color(234, 62, 191));
        job_.setText("Vəzifə");

        jLabel9.setBackground(new java.awt.Color(193, 198, 224));
        jLabel9.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(234, 62, 191));
        jLabel9.setText("Vəzifə: ");

        sts_.setBackground(new java.awt.Color(193, 198, 224));
        sts_.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        sts_.setForeground(new java.awt.Color(234, 62, 191));
        sts_.setText("Status: ");

        jLabel10.setBackground(new java.awt.Color(193, 198, 224));
        jLabel10.setFont(new java.awt.Font("Cantarell", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(234, 62, 191));
        jLabel10.setText("Status: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomre_)
                            .addComponent(email_)
                            .addComponent(ID_)
                            .addComponent(login_)
                            .addComponent(soyad_)
                            .addComponent(coin_))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(ad_)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(msg_num_)
                    .addComponent(job_)
                    .addComponent(sts_))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ad_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(soyad_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(login_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ID_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(email_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nomre_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(coin_))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msg_num_)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(job_))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sts_))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setMyId(int myId) {
        this.myId = myId;
    }

    public static void setJob(int job) {
        showUser.job = job;
    }

    public void init() throws SQLException {
        String jobs[] = {"Sadə istifadəçi", "Menecer", "Baş Menecer", "Developper", "Developper"};
        String sts[] = {"Passiv","Aktiv"};
        d.init();
        String login = d.getLogin(myId);
        String id = String.valueOf(d.getDataInt(1, myId, userTable));
        String name = d.getDataString(6, myId, userTable);
        String surname = d.getDataString(7, myId, userTable);
        String number = d.getDataString(4, myId, userTable);
        String email = d.getDataString(5, myId, userTable);
        int status = d.getDataInt(9, myId, userTable);
        String coin = String.valueOf(d.getDataInt(8, myId, userTable));
        String maxSendMsg = d.getDataString(13, "SELECT * FROM `users` WHERE id = " + String.valueOf(myId) + ";");

        
        ID_.setText(id);
        login_.setText(login);
        ad_.setText(name);
        soyad_.setText(surname);
        nomre_.setText(number);
        email_.setText(email);
        coin_.setText(coin);
        job_.setText(jobs[job]);
        sts_.setText(sts[status]);
        msg_num_.setText(maxSendMsg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new showUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_;
    private javax.swing.JLabel ad_;
    private javax.swing.JLabel coin_;
    private javax.swing.JLabel email_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel job_;
    private javax.swing.JLabel login_;
    private javax.swing.JLabel msg_num_;
    private javax.swing.JLabel nomre_;
    private javax.swing.JLabel soyad_;
    private javax.swing.JLabel sts_;
    // End of variables declaration//GEN-END:variables
}
